version: 2.1
jobs:
  build:
    docker:
      - image: docker/tilt:latest

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: apt install -y python
      - run: apt install -y npm
      - run: npm install -g yarn
      - run: ctlptl create cluster kind --registry=ctlptl-registry && test/test.sh
